(function()
{
	Sidebar.prototype.addCitrixPalette = function()
	{
		var w = 0.5;
		var h = 0.5;
		var s = mxConstants.STYLE_VERTICAL_LABEL_POSITION + '=bottom;aspect=fixed;html=1;' + mxConstants.STYLE_VERTICAL_ALIGN + '=top;strokeColor=none;align=center;outlineConnect=0;shape=mxgraph.citrix.';
		var gn = 'mxgraph.citrix';
		var dt = '';
		this.setCurrentSearchEntryLibrary('citrix');

		this.addPaletteFunctions('citrix', 'Citrix', false,
		[
			this.createVertexTemplateEntry(s + '1u_2u_server;', w * 200, h * 78.2, '', '1U 2U服务器', null, null, this.getTagsForStencil(gn, '1U 2U Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'access_card;', w * 111, h * 150, '', '门禁卡', null, null, this.getTagsForStencil(gn, 'Access Card', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'branch_repeater;', w * 200, h * 78, '', '分支中继器', null, null, this.getTagsForStencil(gn, 'Branch Repeater', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'browser;', w * 95, h * 145, '', '浏览器', null, null, this.getTagsForStencil(gn, 'Browser', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'cache_server;', w * 142, h * 195, '', '缓存服务器', null, null, this.getTagsForStencil(gn, 'Cache Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'calendar;', w * 150, h * 200, '', '日历', null, null, this.getTagsForStencil(gn, 'Calendar', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'cell_phone;', w * 50, h * 120, '', '手机', null, null, this.getTagsForStencil(gn, 'Cell Phone', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'chassis;', w * 275, h * 355, '', '机壳', null, null, this.getTagsForStencil(gn, 'Chassis', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'citrix_hdx;', w * 155, h * 82, '', '思杰HDX', null, null, this.getTagsForStencil(gn, 'Citrix HDX', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'citrix_logo;fillColor=#4E4F53;', w * 320, h * 125, '', 'Citrix徽标', null, null, this.getTagsForStencil(gn, 'Citrix Logo', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'cloud;', w * 190, h * 124, '', '云', null, null, this.getTagsForStencil(gn, 'Cloud', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'command_center;', w * 151, h * 192, '', '指挥中心', null, null, this.getTagsForStencil(gn, 'Command Center', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'database;', w * 85, h * 100, '', '数据库', null, null, this.getTagsForStencil(gn, 'Database', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'database_server;', w * 160, h * 180, '', '数据库服务器', null, null, this.getTagsForStencil(gn, 'Database Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'datacenter;', w * 255, h * 270, '', '数据中心', null, null, this.getTagsForStencil(gn, 'Datacenter', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'desktop;', w * 178, h * 196, '', '桌面', null, null, this.getTagsForStencil(gn, 'Desktop', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'desktop_web;', w * 153, h * 180, '', '桌面网站', null, null, this.getTagsForStencil(gn, 'Desktop Web', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'dhcp_server;', w * 152, h * 180, '', 'DHCP服务器', null, null, this.getTagsForStencil(gn, 'DHCP Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'directory_server;', w * 130, h * 177, '', '目录服务器', null, null, this.getTagsForStencil(gn, 'Directory Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'dns_server;', w * 153, h * 185, '', 'DNS服务器', null, null, this.getTagsForStencil(gn, 'DNS Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'document;', w * 94, h * 144, '', '文件', null, null, this.getTagsForStencil(gn, 'Document', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'edgesight_server;', w * 153, h * 180, '', 'EdgeSight服务器', null, null, this.getTagsForStencil(gn, 'EdgeSight Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'file_server;', w * 142, h * 194, '', '文件服务器', null, null, this.getTagsForStencil(gn, 'File Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'firewall;', w * 150, h * 186, '', '防火墙功能', null, null, this.getTagsForStencil(gn, 'Firewall', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'ftp_server;', w * 142, h * 194, '', 'FTP服务器', null, null, this.getTagsForStencil(gn, 'FTP Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'geolocation_database;', w * 106, h * 98, '', '地理位置数据库', null, null, this.getTagsForStencil(gn, 'Geolocation Database', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'globe;', w * 157, h * 150, '', '地球', null, null, this.getTagsForStencil(gn, 'Globe', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'goto_meeting;fillColor=#FAB616;gradientColor=#E12800;gradientDirection=north;', w * 74, h * 74, '', '去会议', null, null, this.getTagsForStencil(gn, 'GoTo Meeting', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'government;', w * 238, h * 104, '', '政府', null, null, this.getTagsForStencil(gn, 'Government', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'home_office;', w * 160, h * 111, '', '在家办公', null, null, this.getTagsForStencil(gn, 'Home Office', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'hq_enterprise;', w * 184, h * 176, '', '总部/企业', null, null, this.getTagsForStencil(gn, 'HQ Enterprise', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'inspection;', w * 140, h * 130, '', '检查', null, null, this.getTagsForStencil(gn, 'Inspection', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'ip_phone;', w * 153, h * 74, '', 'IP电话', null, null, this.getTagsForStencil(gn, 'IP Phone', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'kiosk;', w * 130, h * 170, '', '亭', null, null, this.getTagsForStencil(gn, 'Kiosk', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'laptop_1;', w * 182, h * 154, '', '笔记本电脑', null, null, this.getTagsForStencil(gn, 'Laptop', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'laptop_2;', w * 232, h * 173, '', '笔记本电脑', null, null, this.getTagsForStencil(gn, 'Laptop', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'license_server;', w * 130, h * 170, '', '许可服务器', null, null, this.getTagsForStencil(gn, 'License Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'merchandising_server;', w * 150, h * 180, '', '采购服务器', null, null, this.getTagsForStencil(gn, 'Merchandising Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'middleware;', w * 228, h * 136, '', '中间件', null, null, this.getTagsForStencil(gn, 'Middleware', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'netscaler_gateway;', w * 200, h * 78, '', 'NetScaler网关', null, null, this.getTagsForStencil(gn, 'NetScaler Gateway', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'netscaler_mpx;', w * 200, h * 78, '', 'NetScaler MPX', null, null, this.getTagsForStencil(gn, 'NetScaler MPX', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'netscaler_sdx;', w * 200, h * 95, '', 'NetScaler SDX', null, null, this.getTagsForStencil(gn, 'NetScaler SDX', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'netscaler_vpx;', w * 194, h * 72, '', 'NetScaler VPX', null, null, this.getTagsForStencil(gn, 'NetScaler VPX', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'pbx_server;', w * 130, h * 170, '', 'PBX服务器', null, null, this.getTagsForStencil(gn, 'PBX Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'pda;', w * 60, h * 122, '', '手机', null, null, this.getTagsForStencil(gn, 'PDA', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'podio;fillColor=#72B8DE;gradientColor=#186BA2;gradientDirection=south;', w * 74, h * 74, '', '波迪奥', null, null, this.getTagsForStencil(gn, 'Podio', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'printer;', w * 140, h * 140, '', '打印机', null, null, this.getTagsForStencil(gn, 'Printer', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'process;', w * 104, h * 124, '', '处理', null, null, this.getTagsForStencil(gn, 'Process', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'provisioning_server;', w * 152, h * 174, '', '供应服务器', null, null, this.getTagsForStencil(gn, 'Provisioning Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'proxy_server;', w * 153, h * 180, '', '代理服务器', null, null, this.getTagsForStencil(gn, 'Proxy Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'radius_server;', w * 151, h * 182, '', '半径服务器', null, null, this.getTagsForStencil(gn, 'Radius Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'remote_office;', w * 184, h * 83, '', '远程办公室', null, null, this.getTagsForStencil(gn, 'Remote Office', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'reporting;', w * 123, h * 138, '', '报告中', null, null, this.getTagsForStencil(gn, 'Reporting', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_appcontroller;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色AppController', null, null, this.getTagsForStencil(gn, 'Role AppController', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_applications;', w * 76, h * 76, '', '角色申请', null, null, this.getTagsForStencil(gn, 'Role Applications', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_cloudbridge;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色CloudBridge', null, null, this.getTagsForStencil(gn, 'Role CloudBridge', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_desktops;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色桌面', null, null, this.getTagsForStencil(gn, 'Role Desktops', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_load_testing_controller;', w * 48, h * 48, '', '角色负载测试控制器', null, null, this.getTagsForStencil(gn, 'Role Load Testing Controller', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_load_testing_launcher;', w * 82, h * 76, '', '角色负载测试启动器', null, null, this.getTagsForStencil(gn, 'Role Load Testing Launcher', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_receiver;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色接收者', null, null, this.getTagsForStencil(gn, 'Role Receiver', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_repeater;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色中继器', null, null, this.getTagsForStencil(gn, 'Role Repeater', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_secure_access;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色安全 Access', null, null, this.getTagsForStencil(gn, 'Role Secure Access', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_security;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色安全', null, null, this.getTagsForStencil(gn, 'Role Security', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_services;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色服务', null, null, this.getTagsForStencil(gn, 'Role Services', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_storefront;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色店面', null, null, this.getTagsForStencil(gn, 'Role StoreFront', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_storefront_services;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色店面服务', null, null, this.getTagsForStencil(gn, 'Role StoreFront Services', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_synchronizer;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色同步器', null, null, this.getTagsForStencil(gn, 'Role Synchronizer', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_xenmobile;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 76, h * 76, '', '角色XenMobile', null, null, this.getTagsForStencil(gn, 'Role XenMobile', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'role_xenmobile_device_manager;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 70, h * 76, '', '角色XenMobile设备管理器', null, null, this.getTagsForStencil(gn, 'Role XenMobile Device Manager', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'router;', w * 110, h * 73, '', '路由器', null, null, this.getTagsForStencil(gn, 'Router', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'security;', w * 81, h * 142, '', '安全', null, null, this.getTagsForStencil(gn, 'Security', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'sharefile;fillColor=#386510;gradientColor=#C6CF2B;gradientDirection=south;', w * 76, h * 76, '', '共享文件', null, null, this.getTagsForStencil(gn, 'ShareFile', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'site;', w * 214, h * 202, '', '现场', null, null, this.getTagsForStencil(gn, 'Site', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'smtp_server;', w * 152, h * 184, '', 'SMTP服务器', null, null, this.getTagsForStencil(gn, 'SMTP Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'storefront_services;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 152, h * 182, '', '店面服务', null, null, this.getTagsForStencil(gn, 'Storefront Services', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'switch;', w * 184, h * 83, '', '开关', null, null, this.getTagsForStencil(gn, 'Switch', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'tablet_1;', w * 122, h * 158, '', '片剂 1', null, null, this.getTagsForStencil(gn, 'Tablet', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'tablet_2;', w * 164, h * 172, '', '片剂 2', null, null, this.getTagsForStencil(gn, 'Tablet', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'thin_client;', w * 142, h * 142, '', '客户端', null, null, this.getTagsForStencil(gn, 'Thin Client', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'tower_server;', w * 130, h * 170, '', '塔式服务器', null, null, this.getTagsForStencil(gn, 'Tower Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'users;', w * 129, h * 110, '', 'Users', null, null, this.getTagsForStencil(gn, 'Users', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'user_control;', w * 206, h * 168, '', '用户控制', null, null, this.getTagsForStencil(gn, 'User Control', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'web_server;', w * 153, h * 180, '', '网络服务器', null, null, this.getTagsForStencil(gn, 'Web Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'web_service;', w * 126, h * 120, '', '网络服务', null, null, this.getTagsForStencil(gn, 'Web Service', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'worxenroll;fillColor=#386510;gradientColor=#C6CF2B;gradientDirection=south;', w * 76, h * 76, '', 'Worx注册', null, null, this.getTagsForStencil(gn, 'WorxEnroll', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'worxhome;fillColor=#DB9EFF;gradientColor=#712FA2;gradientDirection=south;', w * 76, h * 76, '', 'WorxHome', null, null, this.getTagsForStencil(gn, 'WorxHome', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'worxmail;fillColor=#112356;gradientColor=#63AFC6;gradientDirection=south;', w * 76, h * 76, '', 'WorxMail', null, null, this.getTagsForStencil(gn, 'WorxMail', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'worxweb;fillColor=#2A3437;gradientColor=#B8B9B9;gradientDirection=south;', w * 76, h * 76, '', 'WorxWeb', null, null, this.getTagsForStencil(gn, 'WorxWeb', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenapp_server;', w * 152, h * 178, '', 'XenApp服务器', null, null, this.getTagsForStencil(gn, 'XenApp Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenapp_services;', w * 152, h * 180, '', 'XenApp服务', null, null, this.getTagsForStencil(gn, 'XenApp Services', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenapp_web;', w * 152, h * 180, '', 'XenApp网站', null, null, this.getTagsForStencil(gn, 'XenApp Web', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xencenter;', w * 152, h * 178, '', 'XenCenter', null, null, this.getTagsForStencil(gn, 'XenCenter', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenclient;', w * 182, h * 154, '', 'XenClient', null, null, this.getTagsForStencil(gn, 'XenClient', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenclient_synchronizer;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 152, h * 182, '', 'XenClient同步器', null, null, this.getTagsForStencil(gn, 'Synchronizer', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xendesktop_server;', w * 150, h * 182, '', 'XenDesktop Server', null, null, this.getTagsForStencil(gn, 'XenDesktop Server', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenmobile;fillColor=#CCCCCC;gradientColor=#000000;gradientDirection=south;', w * 140, h * 178, '', 'XenMobile', null, null, this.getTagsForStencil(gn, 'XenMobile', dt).join(' ')),
			this.createVertexTemplateEntry(s + 'xenserver;', w * 153, h * 180, '', 'XenServer', null, null, this.getTagsForStencil(gn, 'XenServer', dt).join(' '))
		]);

		this.setCurrentSearchEntryLibrary();
	};
})();
